// Phase 5 — event-driven daily summaries.
//
// Triggered when:
//   1. a notable/critical alert lands on TOPIC.ALERT (debounced)
//   2. an admin asks the chat agent for "today's summary" (manual)
//   3. day rolls over (we lazy-finalize yesterday on first call after midnight)
//
// Cost story:
//   - Stats math is pure SQL (cheap, <5ms typical).
//   - Prose is generated by the LOCAL Gemma model on $OLLAMA_BASE
//     (free, ~500ms-2s on a CPU model, ~200-500ms on GPU).
//   - Per (tenant, day, scope) we enforce MIN_REGEN_MS so one busy camera
//     can't burn Gemma capacity. Subsequent triggers within the cooldown
//     coalesce into a single trailing-edge regen (debounce).
//
// This module deliberately does NOT touch GPT (T3). Daily prose is a
// quintessential "lots of cheap text" workload — exactly what local
// inference is for.

import { subscribe } from "./eventbus.mjs";
import { TOPIC } from "./types.mjs";
import {
  aggregateDailyStats,
  upsertDailySummary,
  getDailySummary,
  dayKeyUtc,
} from "../db.mjs";

const OLLAMA_BASE = process.env.OLLAMA_BASE ?? "http://192.168.0.137:11434";
const SUMMARY_MODEL = process.env.OLLAMA_TEXT_MODEL ?? "gemma3:4b";
const SUMMARY_TIMEOUT_MS = Number(process.env.OLLAMA_TEXT_TIMEOUT_MS ?? 12_000);
const SUMMARY_KEEP_ALIVE = process.env.OLLAMA_TEXT_KEEP_ALIVE ?? "10m";

// Trailing-edge debounce: when an alert fires, we wait this long before
// running so coincident alerts coalesce. 8s is short enough that the chat
// "what's happened today?" feels live, long enough to dedupe burst alerts.
const REGEN_DEBOUNCE_MS = Number(process.env.SUMMARY_REGEN_DEBOUNCE_MS ?? 8_000);
// Hard floor between successive regens for the same (day, scope). Even if
// alerts keep arriving, we won't regen more than once per this window.
const MIN_REGEN_MS = Number(process.env.SUMMARY_MIN_REGEN_MS ?? 60_000);

let started = false;
let unsubscribeAlert = null;

// scope-key -> {timer, lastRunAt}
const _state = new Map();
function _key(tenant_id, day, scope) { return `${tenant_id}|${day}|${scope}`; }

// -------------------------------------------------------------------------
// LLM call (text-only Ollama)
// -------------------------------------------------------------------------

/**
 * Build a stable, terse prompt that turns aggregated stats into prose. We
 * deliberately give Gemma JSON, not natural language — the model is much
 * better at "summarize this structure" than free-text inference.
 */
function buildPrompt({ stats, day, scope }) {
  const scopeLabel = scope === "tenant" ? "across all cameras"
    : scope.startsWith("camera:") ? `for camera "${scope.slice(7)}"`
    : `for ${scope}`;
  const compact = {
    day,
    scope_label: scopeLabel,
    totals: stats.totals,
    by_camera: (stats.by_camera ?? []).slice(0, 6),
    by_origin: (stats.by_origin ?? []).slice(0, 6),
    top_alert_reasons: (stats.top_alert_reasons ?? []).slice(0, 5),
    people_seen: (stats.people_seen ?? []).slice(0, 6),
  };
  return [
    "You are a security operations assistant. Write a short factual",
    "summary (3-5 sentences) of today's camera activity using ONLY the",
    "JSON below. Do not invent events. If totals.events is 0, say so.",
    "Lead with severity counts; mention top alert reasons; mention which",
    "camera was busiest; mention who was seen if there are non-empty",
    "people_seen entries. Plain prose, no bullets, no markdown.",
    "",
    "INPUT:",
    JSON.stringify(compact),
    "",
    "SUMMARY:",
  ].join("\n");
}

/**
 * Text-only call to Ollama /api/chat. Mirrors tier2.callOllamaVision but
 * without an image payload and with `num_predict` raised for prose length.
 *
 * Returns { ok, text, tookMs, model, error? }.
 */
export async function callOllamaText({
  prompt,
  model = SUMMARY_MODEL,
  timeoutMs = SUMMARY_TIMEOUT_MS,
  fetchImpl = fetch,
} = {}) {
  if (!prompt || typeof prompt !== "string") {
    return { ok: false, error: "missing_prompt", text: "", tookMs: 0, model };
  }
  const body = {
    model,
    stream: false,
    keep_alive: SUMMARY_KEEP_ALIVE,
    messages: [{ role: "user", content: prompt }],
    options: { temperature: 0.2, num_predict: 220 },
  };
  const t0 = Date.now();
  try {
    const res = await fetchImpl(`${OLLAMA_BASE}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(timeoutMs),
    });
    const tookMs = Date.now() - t0;
    if (!res.ok) {
      return { ok: false, error: `ollama_${res.status}`, text: "", tookMs, model };
    }
    const json = await res.json();
    const text = (json?.message?.content ?? "").trim();
    return { ok: true, text, tookMs, model };
  } catch (err) {
    return {
      ok: false,
      error: err?.name === "TimeoutError" ? "timeout" : err?.message ?? "fetch_failed",
      text: "",
      tookMs: Date.now() - t0,
      model,
    };
  }
}

// -------------------------------------------------------------------------
// Stats-only fallback — works even when Gemma is unreachable
// -------------------------------------------------------------------------

/**
 * Deterministic English render of the same stats Gemma would see. Used as
 * a fallback when the LLM call fails so we always have SOMETHING to show.
 */
export function statsToProse(stats) {
  const t = stats.totals ?? {};
  if (!t.events) return "No events recorded today.";
  const parts = [];
  parts.push(`${t.events} event${t.events === 1 ? "" : "s"} today`);
  const sevBits = [];
  if (t.critical) sevBits.push(`${t.critical} critical`);
  if (t.notable) sevBits.push(`${t.notable} notable`);
  if (t.normal) sevBits.push(`${t.normal} normal`);
  if (sevBits.length) parts.push(`(${sevBits.join(", ")})`);
  let lead = parts.join(" ") + ".";

  const top = stats.by_camera?.[0];
  let camLine = "";
  if (top && stats.by_camera.length > 1) {
    camLine = ` Busiest camera: ${top.camera} (${top.n}).`;
  } else if (top && stats.by_camera.length === 1) {
    camLine = ` All on ${top.camera}.`;
  }

  const reasons = (stats.top_alert_reasons ?? []).slice(0, 3)
    .map((r) => `${r.alert_type} (${r.n})`).join(", ");
  const reasonLine = reasons ? ` Top alert types: ${reasons}.` : "";

  const known = (stats.people_seen ?? []).filter((p) => p.who !== "(unknown)");
  const unknown = (stats.people_seen ?? []).filter((p) => p.who === "(unknown)");
  let peopleLine = "";
  if (known.length) {
    peopleLine = ` Known people seen: ${known.slice(0, 4).map((p) => `${p.who} (${p.sightings})`).join(", ")}.`;
  }
  if (unknown.length && unknown[0].sightings) {
    peopleLine += ` ${unknown[0].sightings} unknown face sighting${unknown[0].sightings === 1 ? "" : "s"}.`;
  }
  return (lead + camLine + reasonLine + peopleLine).trim();
}

// -------------------------------------------------------------------------
// Public regen API
// -------------------------------------------------------------------------

/**
 * Regenerate the summary for a (tenant, day, scope) triplet. Idempotent —
 * if cooldown is active and `force=false`, returns the existing row
 * unchanged. If Gemma fails, persists the deterministic fallback prose.
 *
 * @param {{
 *   db: object, tenant_id?: string, day?: string, scope: string,
 *   force?: boolean, fetchImpl?: typeof fetch, model?: string,
 * }} args
 */
export async function regenerate({
  db,
  tenant_id = "default",
  day = dayKeyUtc(),
  scope,
  force = false,
  fetchImpl,
  model = SUMMARY_MODEL,
}) {
  if (!db) throw new Error("db required");
  if (!scope) throw new Error("scope required");

  const k = _key(tenant_id, day, scope);
  const now = Date.now();
  const last = _state.get(k);
  if (!force && last?.lastRunAt && now - last.lastRunAt < MIN_REGEN_MS) {
    const existing = getDailySummary(db, { tenant_id, day, scope });
    if (existing) {
      return { ...existing, regen_skipped: true, reason: "cooldown" };
    }
  }

  const stats = aggregateDailyStats(db, { tenant_id, day, scope });
  const prompt = buildPrompt({ stats, day, scope });
  const ll = await callOllamaText({ prompt, model, fetchImpl });
  const useLlm = ll.ok && ll.text;
  const summary = useLlm ? ll.text : statsToProse(stats);

  const row = upsertDailySummary(db, {
    tenant_id, day, scope, stats, summary,
    model: useLlm ? ll.model : "stats_fallback",
    last_event_id: stats.totals.last_event_id,
    generated_in_ms: ll.tookMs ?? null,
  });

  _state.set(k, { lastRunAt: Date.now(), timer: null });
  return { ...row, regen_skipped: false, llm_ok: ll.ok, llm_error: ll.ok ? null : ll.error };
}

/**
 * Schedule a debounced regen. Subsequent calls within REGEN_DEBOUNCE_MS
 * coalesce into a single trailing call. Safe to call from inside event
 * handlers.
 */
export function scheduleRegen({ db, tenant_id = "default", day = dayKeyUtc(), scope }) {
  if (!db || !scope) return;
  const k = _key(tenant_id, day, scope);
  const cur = _state.get(k) ?? {};
  if (cur.timer) clearTimeout(cur.timer);
  cur.timer = setTimeout(() => {
    cur.timer = null;
    regenerate({ db, tenant_id, day, scope }).catch((err) => {
      console.warn("[summary] scheduled regen failed:", err?.message);
    });
  }, REGEN_DEBOUNCE_MS);
  _state.set(k, cur);
}

/**
 * Wire the summary builder to TOPIC.ALERT on the bus. Every alert event
 * schedules BOTH a tenant-wide and per-camera regen. Idempotent.
 *
 * @param {{ db: object }} deps
 */
export function start({ db } = {}) {
  if (started) return;
  if (!db) throw new Error("summary.start: db required");
  started = true;
  unsubscribeAlert = subscribe(TOPIC.ALERT, (ev) => {
    try {
      const tenant_id = ev?.tenant_id ?? "default";
      const day = dayKeyUtc(ev?.created_at_ms ? new Date(ev.created_at_ms) : new Date());
      const camera = ev?.camera || null;
      scheduleRegen({ db, tenant_id, day, scope: "tenant" });
      if (camera) scheduleRegen({ db, tenant_id, day, scope: `camera:${camera}` });
    } catch (err) {
      console.warn("[summary] alert handler failed:", err?.message);
    }
  });
}

export function stop() {
  if (unsubscribeAlert) unsubscribeAlert();
  unsubscribeAlert = null;
  for (const v of _state.values()) {
    if (v.timer) clearTimeout(v.timer);
  }
  _state.clear();
  started = false;
}

export function inspect() {
  const pending = [];
  for (const [k, v] of _state.entries()) {
    pending.push({
      key: k,
      has_pending_regen: Boolean(v.timer),
      last_run_at: v.lastRunAt ?? null,
      ms_since_last: v.lastRunAt ? Date.now() - v.lastRunAt : null,
    });
  }
  return {
    started,
    model: SUMMARY_MODEL,
    base: OLLAMA_BASE,
    debounce_ms: REGEN_DEBOUNCE_MS,
    min_regen_ms: MIN_REGEN_MS,
    pending,
  };
}

export const SUMMARY_CONFIG = Object.freeze({
  model: SUMMARY_MODEL,
  base: OLLAMA_BASE,
  debounce_ms: REGEN_DEBOUNCE_MS,
  min_regen_ms: MIN_REGEN_MS,
  timeout_ms: SUMMARY_TIMEOUT_MS,
});
