#!/usr/bin/env bash
# Inserts a `location /demo/` alias block into the odyn-aware nginx
# site config so the homepage can pull a baked overlay MP4 from
# /var/www/odyn-aware/data/demo/ without going through admin auth.
# Re-running this script is a no-op if the block is already present.
set -euo pipefail

SITE=/etc/nginx/sites-enabled/odyn-aware

if grep -q '^[[:space:]]*location /demo/' "$SITE"; then
  echo "already patched"
  exit 0
fi

NEW_BLOCK=$(cat <<'NGX'

    # /demo/* - homepage hero assets baked from real eval runs.
    # Lives OUTSIDE dist/ so npm run build does not wipe them.
    # See tools/bake_demo_overlay.py for how aurora-tracking.mp4 is
    # produced. Long cache; the file is regenerated by hand on demand.
    location /demo/ {
        alias /var/www/odyn-aware/data/demo/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        try_files $uri =404;
    }
NGX
)

awk -v block="$NEW_BLOCK" '
  { print }
  /^[[:space:]]*root \/var\/www\/odyn-aware\/current\/dist;[[:space:]]*$/ && !done {
    print block
    done = 1
  }
' "$SITE" > /tmp/odyn-aware.new

mv /tmp/odyn-aware.new "$SITE"
chown root:root "$SITE"
chmod 644 "$SITE"
echo "patched"
