// Phase-11B persisted track timeline — schema + CRUD.
//
// Sidecar to keep server/db.mjs under the 1000-line refactor trigger.
//
// `track_observations` records every persistent ByteTrack session the
// tracker sidecar exposes. One row per session_id (UUID generated by
// the tracker when the track first appears), updated periodically by
// /api/tracker/ingest with the latest bbox + last_seen_ms.
//
// Sessions are auto-closed by closeStaleTrackObservations when their
// last_seen_ms is older than the stale threshold — that lets us avoid
// requiring the sidecar to send an explicit "this track ended"
// message. Cheaper protocol, idempotent, robust to crashes.
//
// Privacy note: bbox + label only, no images. The sidecar already
// suppresses unverified static blobs upstream (Phase-11A), so this
// table is a record of "things the operator actually saw boxed".

/**
 * Apply the tracks schema. Idempotent — safe to call on every boot.
 * Wired from openDb().
 */
export function applyTracksSchema(db) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS track_observations (
      session_id     TEXT PRIMARY KEY,
      camera         TEXT NOT NULL,
      track_id       INTEGER NOT NULL,
      label          TEXT NOT NULL,
      conf           REAL NOT NULL,
      bbox_x         REAL NOT NULL,
      bbox_y         REAL NOT NULL,
      bbox_w         REAL NOT NULL,
      bbox_h         REAL NOT NULL,
      motion         TEXT,
      verified       INTEGER,
      frames_seen    INTEGER NOT NULL DEFAULT 1,
      first_seen_ms  INTEGER NOT NULL,
      last_seen_ms   INTEGER NOT NULL,
      closed_at_ms   INTEGER,
      inserted_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
      updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
    );
    CREATE INDEX IF NOT EXISTS idx_track_obs_camera_recent
      ON track_observations(camera, last_seen_ms DESC);
    CREATE INDEX IF NOT EXISTS idx_track_obs_open
      ON track_observations(closed_at_ms, last_seen_ms DESC)
      WHERE closed_at_ms IS NULL;
    CREATE INDEX IF NOT EXISTS idx_track_obs_label
      ON track_observations(label, last_seen_ms DESC);
  `);
}

// ---- ingest -------------------------------------------------------------

/**
 * Bulk upsert from the tracker sidecar. Each observation MUST carry a
 * session_id (UUID-ish string) — that's the natural key. We update
 * last_seen_ms and the latest bbox/conf/motion/verified each time.
 *
 * `closed_at_ms` is preserved on conflict — once a session is closed,
 * a subsequent batch from a slow/laggy client doesn't reopen it.
 *
 * Returns { upserted, skipped }.
 */
export function upsertTrackObservations(db, camera, observations) {
  if (!Array.isArray(observations) || observations.length === 0) {
    return { upserted: 0, skipped: 0 };
  }
  const stmt = db.prepare(`
    INSERT INTO track_observations
      (session_id, camera, track_id, label, conf,
       bbox_x, bbox_y, bbox_w, bbox_h,
       motion, verified, frames_seen,
       first_seen_ms, last_seen_ms, updated_at)
    VALUES
      (@session_id, @camera, @track_id, @label, @conf,
       @bbox_x, @bbox_y, @bbox_w, @bbox_h,
       @motion, @verified, @frames_seen,
       @first_seen_ms, @last_seen_ms,
       strftime('%Y-%m-%dT%H:%M:%fZ','now'))
    ON CONFLICT(session_id) DO UPDATE SET
      label         = excluded.label,
      conf          = excluded.conf,
      bbox_x        = excluded.bbox_x,
      bbox_y        = excluded.bbox_y,
      bbox_w        = excluded.bbox_w,
      bbox_h        = excluded.bbox_h,
      motion        = excluded.motion,
      verified      = excluded.verified,
      frames_seen   = excluded.frames_seen,
      last_seen_ms  = MAX(track_observations.last_seen_ms, excluded.last_seen_ms),
      updated_at    = strftime('%Y-%m-%dT%H:%M:%fZ','now')
    -- Don't reopen a closed session. The tracker may briefly re-see
    -- a track right after we closed it; we want to leave it closed
    -- and the next sighting will get a fresh session_id from the
    -- tracker (it generates a new UUID on track-id reuse).
    WHERE track_observations.closed_at_ms IS NULL
  `);

  let upserted = 0;
  let skipped = 0;
  const tx = db.transaction((rows) => {
    for (const o of rows) {
      if (!isValidObservation(o)) {
        skipped += 1;
        continue;
      }
      const result = stmt.run({
        session_id: o.session_id,
        camera,
        track_id: o.track_id,
        label: o.label,
        conf: o.conf,
        bbox_x: o.bbox[0],
        bbox_y: o.bbox[1],
        bbox_w: o.bbox[2],
        bbox_h: o.bbox[3],
        motion: o.motion ?? null,
        // SQLite has no boolean; store 1/0/NULL.
        verified:
          o.verified === true ? 1 : o.verified === false ? 0 : null,
        frames_seen: o.frames_seen ?? 1,
        first_seen_ms: o.first_seen_ms,
        last_seen_ms: o.last_seen_ms,
      });
      // result.changes can be 0 if the WHERE blocked the upsert (closed)
      if (result.changes > 0) upserted += 1;
      else skipped += 1;
    }
  });
  tx(observations);
  return { upserted, skipped };
}

function isValidObservation(o) {
  return (
    o &&
    typeof o.session_id === "string" &&
    o.session_id.length >= 8 &&
    o.session_id.length <= 64 &&
    Number.isInteger(o.track_id) &&
    typeof o.label === "string" &&
    o.label.length > 0 &&
    o.label.length <= 64 &&
    typeof o.conf === "number" &&
    Array.isArray(o.bbox) &&
    o.bbox.length === 4 &&
    o.bbox.every((v) => typeof v === "number" && v >= 0 && v <= 1.5) &&
    Number.isInteger(o.first_seen_ms) &&
    Number.isInteger(o.last_seen_ms)
  );
}

// ---- maintenance --------------------------------------------------------

/**
 * Close any open observation whose last_seen_ms is older than
 * (now_ms - graceMs). Returns the count closed.
 *
 * Safe to call on a timer; idempotent.
 */
export function closeStaleTrackObservations(db, { graceMs = 30_000 } = {}) {
  const cutoff = Date.now() - graceMs;
  const stmt = db.prepare(`
    UPDATE track_observations
       SET closed_at_ms = ?,
           updated_at   = strftime('%Y-%m-%dT%H:%M:%fZ','now')
     WHERE closed_at_ms IS NULL
       AND last_seen_ms < ?
  `);
  const res = stmt.run(Date.now(), cutoff);
  return res.changes;
}

// ---- read ---------------------------------------------------------------

/**
 * Recent observations for the admin timeline. Defaults to "open or
 * closed within the last 24h", camera filter optional.
 *
 * @param {object} db better-sqlite3 db
 * @param {object} opts
 * @param {string|null} opts.camera   filter to one camera (optional)
 * @param {string|null} opts.label    filter to one label (optional)
 * @param {number}      opts.sinceMs  earliest last_seen_ms (default 24h ago)
 * @param {boolean}     opts.openOnly only currently-open sessions
 * @param {number}      opts.limit    page size (max 500)
 */
export function listTrackObservations(
  db,
  {
    camera = null,
    label = null,
    sinceMs = Date.now() - 24 * 60 * 60 * 1000,
    openOnly = false,
    limit = 200,
  } = {},
) {
  const lim = Math.min(Math.max(Number(limit) || 200, 1), 500);
  const filters = ["last_seen_ms >= ?"];
  const args = [sinceMs];
  if (camera) {
    filters.push("camera = ?");
    args.push(camera);
  }
  if (label) {
    filters.push("label = ?");
    args.push(label);
  }
  if (openOnly) filters.push("closed_at_ms IS NULL");
  args.push(lim);
  const sql = `
    SELECT session_id, camera, track_id, label, conf,
           bbox_x, bbox_y, bbox_w, bbox_h,
           motion, verified, frames_seen,
           first_seen_ms, last_seen_ms, closed_at_ms,
           inserted_at, updated_at
      FROM track_observations
     WHERE ${filters.join(" AND ")}
  ORDER BY last_seen_ms DESC
     LIMIT ?
  `;
  return db.prepare(sql).all(...args);
}

/**
 * Aggregated counts for a small operator-facing dashboard. Returns a
 * { byLabel, byCamera, totals } shape.
 */
export function trackObservationCounts(
  db,
  { sinceMs = Date.now() - 24 * 60 * 60 * 1000 } = {},
) {
  const byLabel = db
    .prepare(
      `SELECT label, COUNT(*) AS n
         FROM track_observations
        WHERE last_seen_ms >= ?
     GROUP BY label
     ORDER BY n DESC`,
    )
    .all(sinceMs);
  const byCamera = db
    .prepare(
      `SELECT camera, COUNT(*) AS n
         FROM track_observations
        WHERE last_seen_ms >= ?
     GROUP BY camera
     ORDER BY n DESC`,
    )
    .all(sinceMs);
  const totals = db
    .prepare(
      `SELECT COUNT(*) AS total,
              SUM(CASE WHEN closed_at_ms IS NULL THEN 1 ELSE 0 END) AS open_sessions,
              SUM(CASE WHEN verified = 1 THEN 1 ELSE 0 END)         AS verified_static,
              SUM(CASE WHEN motion = 'moving' THEN 1 ELSE 0 END)    AS moving
         FROM track_observations
        WHERE last_seen_ms >= ?`,
    )
    .get(sinceMs);
  return { byLabel, byCamera, totals };
}
