/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTracksRouteImport } from './routes/admin/tracks'
import { Route as AdminMapRouteImport } from './routes/admin/map'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLiveRouteImport } from './routes/admin/live'
import { Route as AdminFacesRouteImport } from './routes/admin/faces'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTracksRoute = AdminTracksRouteImport.update({
  id: '/admin/tracks',
  path: '/admin/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/admin/map',
  path: '/admin/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacesRoute = AdminFacesRouteImport.update({
  id: '/admin/faces',
  path: '/admin/faces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/alerts'
    | '/admin/faces'
    | '/admin/live'
    | '/admin/login'
    | '/admin/map'
    | '/admin/tracks'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/alerts'
    | '/admin/faces'
    | '/admin/live'
    | '/admin/login'
    | '/admin/map'
    | '/admin/tracks'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/alerts'
    | '/admin/faces'
    | '/admin/live'
    | '/admin/login'
    | '/admin/map'
    | '/admin/tracks'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminFacesRoute: typeof AdminFacesRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminTracksRoute: typeof AdminTracksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tracks': {
      id: '/admin/tracks'
      path: '/admin/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AdminTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/admin/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faces': {
      id: '/admin/faces'
      path: '/admin/faces'
      fullPath: '/admin/faces'
      preLoaderRoute: typeof AdminFacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminFacesRoute: AdminFacesRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMapRoute: AdminMapRoute,
  AdminTracksRoute: AdminTracksRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
